### PR TITLE
Fixed the issue with setting of the global options

### PR DESCRIPTION
**Pull request by ashfaqnisar**
Exporting the aggregatePaginate directly to set the global options.

### CODE REVIEW

**Comment by ashfaqnisar** [comment]
This PR fixes the issue #37

**Comment by ashfaqnisar** [comment]
Do we need aggregatePaginate or just paginate while setting the global options

**Comment by ashfaqnisar** [comment]
Hey @aravindnc, it would be great if you could merge this.

**Comment by aravindnc** [comment]
@ashfaqnisar Thanks. But any idea why the build is getting errored.

**Comment by aravindnc** [comment]
> Do we need aggregatePaginate or just paginate while setting the global options

It should be aggregatePaginate  since there is already another plugin for paginate.

**Comment by ashfaqnisar** [comment]
> @ashfaqnisar Thanks. But any idea why the build is getting errored.

I think it was due to the minimum node version.

**Pull request merged**
